---
#
# Basic server initialization
#

- name: Write hostname using jinja2
  ansible.builtin.template:
    src: templates/test.j2
    dest: /tmp/hostname

- name: Template ".bashrc" file
  ansible.builtin.template:
    src: templates/.bashrc
    dest: /home/andy/.bashrc
    owner: andy
    group: andy
    mode: 0644
    backup: yes

- name: Create ~/.docker directory
  tags: ghcr
  ansible.builtin.file:
    path: /home/andy/.docker
    state: directory
    owner: andy
    group: andy
    mode: 0700
    recurse: yes

- name: Template credentials for Gihub Container Registry (ghcr.io)
  tags: ghcr
  ansible.builtin.template:
    src: templates/.git-credentials
    dest: /home/andy/.git-credentials
    owner: andy
    group: andy
    mode: 0600
    backup: yes

- name: Copy git configuration
  tags: git
  ansible.builtin.copy:
    src: templates/.gitconfig
    dest: /home/andy/.gitconfig
    owner: andy
    group: andy
    mode: 0600
    backup: yes

- name: Template gGithub credentials
  tags: ghcr
  ansible.builtin.template:
    src: templates/.git-credentials
    dest: /home/andy/.git-credentials
    owner: andy
    group: andy
    mode: 0600
    backup: yes

# - name: Pause for 5 seconds to build app cache
#   ansible.builtin.pause:
#     seconds: 5
# #   minutes: 5

# - name: Pause until you can verify updates to an application were successful
#   ansible.builtin.pause:

# - name: Make sure container is up and running
#   ansible.builtin.pause:
#     prompt: "Make sure container is up and running"

# - name: Pause to get some sensitive input
#   ansible.builtin.pause:
#     prompt: "Enter a secret"
#     echo: no
